version: '2.30.0'
services:
  db:
    image: postgres:12.21
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB: ${DB}
      SECRET: ${SECRET}
      PORT: ${PORT}
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db
